version: "3.8"

services:
  # PostgreSQL Service
  postgres:
    image: postgres:16-alpine
    container_name: vuln-tracker
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-vulntracker}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vuln-tracker-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-vulntracker}?schema=public
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_here}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
